            <div class="center rounded social">
              <div class="g-plus" data-href="https://plus.google.com/104376173446857539292?rel=publisher" data-width="200" data-height="131" data-theme="light"></div>
              <div class="facebook"><!-- Facebook Badge START --><a href="https://www.facebook.com/VirginiaHillsPool" target="_TOP" style="font-family: &quot;lucida grande&quot;,tahoma,verdana,arial,sans-serif; font-size: 11px; font-variant: normal; font-style: normal; font-weight: normal; color: #3B5998; text-decoration: none;" title="Virginia Hills Pool">Virginia Hills Pool</a><br/><a href="https://www.facebook.com/VirginiaHillsPool" target="_TOP" title="Virginia Hills Pool"><img src="https://www.facebook.com/badge/358066327590666.2254.217512803.png" style="border: 0px;" /></a><!-- Facebook Badge END --></div>
            </div>
          </div>
        </div>
      </div>
      <div id="ft">
        <div class="center rounded bubbles-small">
          <div class="footer rounded">
            <address>
              Virginia Hills Swim Club ■ <a class="c8"
              href=
              "mailto:info@vahillspool.org">info@vahillspool.org</a><br>
              6500 Virginia Hills Pool Drive ■ P.O. Box 10233<br>
              Alexandria, VA 22310<br>
              Guard Shack (during pool hours): (703) 329-2360
            </address>
          </div>
          <!-- Geocode locations -->
          <span style="display:none;">
            <span class="geo">
              <span class="latitude">38.76639</span>;
              <span class="longitude">-77.114311</span>
            </span>
            <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#">
              <geo:Point>
                <geo:lat>38.76639</geo:lat>
                <geo:long>-77.114311</geo:long>
              </geo:Point> 
            </rdf:RDF>
          </span>
          <a class="webmaster"
             href=
             "mailto:webmaster@vahillspool.org">webmaster@vahillspool.org</a><br>
        </div>
      </div>
    </div>  
    <script type="text/javascript">
      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>
    <!-- Start of StatCounter Code for Default Guide -->
    <script type="text/javascript">
      var sc_project=7455206; 
      var sc_invisible=1; 
      var sc_security="3236c735"; 
    </script>
    <script type="text/javascript"
      src="http://www.statcounter.com/counter/counter.js"></script>
      <noscript><div class="statcounter"><a title="tumblr
      counter" href="http://statcounter.com/tumblr/"
      target="_blank"><img class="statcounter"
      src="http://c.statcounter.com/7455206/0/3236c735/1/"
      alt="tumblr counter"></a></div></noscript>
    <!-- End of StatCounter Code for Default Guide -->
  </body>
</html>
