            <div class="center rounded">
              <div class="g-plusone" data-size="small" data-annotation="inline" data-width="180"></div>
            </div>
          </div>
        </div>
      </div>
      <div id="ft">
        <div class="center rounded bubbles-small">
          <div class="footer rounded">
            <address>
              Virginia Hills Swim Club ■ <a class="c8"
              href=
              "mailto:info@vahillspool.org">info@vahillspool.org</a><br>
              6500 Robinson Drive ■ P.O. Box 10233<br>
              Alexandria, VA 22310<br>
              Guard Shack (during pool hours): (703) 960-9717
            </address>
          </div>
          <!-- Geocode locations -->
          <span style="display:none;">
            <span class="geo">
              <span class="latitude">38.76639</span>;
              <span class="longitude">-77.114311</span>
            </span>
            <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#">
              <geo:Point>
                <geo:lat>38.76639</geo:lat>
                <geo:long>-77.114311</geo:long>
              </geo:Point> 
            </rdf:RDF>
          </span>
          <a class="webmaster"
             href=
             "mailto:webmaster@vahillspool.org">webmaster@vahillspool.org</a><br>
        </div>
      </div>
    </div>  
    <script type="text/javascript">
      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>
  </body>
</html>
