<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" 
"http://www.w3.org/TR/html4/strict.dtd"> 
<html>
  <head>
    <meta name="generator" content=
    "HTML Tidy for Windows (vers 14 February 2006), see www.w3.org">
    <title>
      <?php echo $siteTitle; ?> - Virginia Hills Pool, Alexandria, VA
    </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="geo.position" content="38.76639;-77.114311">
    <meta name="geo.placename" content="Alexandria, Virginia, United States">
    <meta name="geo.region" content="us-va">
    <meta name="ICBM" content="38.76639;-77.114311">
    <meta name="google-site-verification" content="oWVHaIbsW3g_HyzkSiUBJT6v3sHc2ECLIO9LSN0zhIE" />
    <link rel="stylesheet" href="/css/vahillspool.css" type="text/css" media=
    "screen">
    <script type="text/JavaScript" src="/js/curvycorners.js"></script>
    <script type="text/JavaScript" src="/js/jquery.js"></script>
  </head>
  <body>
    <div id="doc" class="yui-t2">
      <div id="hd">
        <div class="rounded">
          <a href="index.php">
          <img src="/images/header.png" width="800" height="159" border="0"
          alt="Virginia Hills Pool Home">
          </a>
        </div>
      </div>
      <div id="bd">
        <div class="yui-b">
          <?php include_once "navigation.inc"; ?>
        </div>
        <div id="yui-main">
          <div class="yui-b">
