<?php
  include_once "../vahillspool.conf.php";
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" 
"http://www.w3.org/TR/html4/strict.dtd"> 
<html>
  <head>
    <meta name="generator" content=
    "HTML Tidy for Windows (vers 14 February 2006), see www.w3.org">
    <title>
      <?php echo $siteTitle; ?> - Virginia Hills Pool, Alexandria, VA
    </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="geo.position" content="38.76639;-77.114311">
    <meta name="geo.placename" content="Alexandria, Virginia, United States">
    <meta name="geo.region" content="us-va">
    <meta name="ICBM" content="38.76639;-77.114311">
    <meta name="google-site-verification" content="oWVHaIbsW3g_HyzkSiUBJT6v3sHc2ECLIO9LSN0zhIE" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="stylesheet" href="<?php echo $root; ?>/css/vahillspool.min.css" type="text/css" media=
    "screen">
    <!-- <script type="text/JavaScript" src="<?php echo $root; ?>/js/curvycorners.js"></script> -->
    <script type="text/JavaScript" src="<?php echo $root; ?>/js/jquery.js"></script>
    <!-- Google Analytics -->
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-9635197-1']);
      _gaq.push(['_setDomainName', 'vahillspool.org']);
      _gaq.push(['_trackPageview']);
      _gaq.push(['_trackPageLoadTime']);
      
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
    <!-- Google Plus badge -->
    <script type="text/javascript">
      window.___gcfg = {lang: 'en'};
      (function() 
      {var po = document.createElement("script");
      po.type = "text/javascript"; po.async = true;po.src = "https://apis.google.com/js/plusone.js";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(po, s);
      })();
    </script>
  </head>
  <body>
    <div id="doc" class="yui-t2">
      <div id="hd">
        <div class="rounded">
          <?php if(strtotime("2012-05-28") - time() > 0) { ?>
          <iframe style="position:relative; float:right; margin-bottom:-80px;" src="http://free.timeanddate.com/countdown/i32vfl79/n263/cf12/cm0/cu4/ct0/cs1/ca0/co1/cr0/ss1/cac333/cpc333/pct/tcfff/fs100/szw448/szh189/tatPool%20Opening%20in%3A/tac333/tptPool%20is%20open!/tpc333/iso2012-05-26T12:00:00/bac333/pa5" frameborder="0" width="219" height="77"></iframe>
          <?php } ?>
          <a href="index.php">
          <img src="<?php echo $root; ?>/images/header.png" width="800" height="159"
            alt="Virginia Hills Pool Home">
          </a>
        </div>
      </div>
      <div id="bd">
        <div class="yui-b">
          <?php include_once "navigation.inc"; ?>
        </div>
        <div id="yui-main">
          <div class="yui-b">
