<div class="center">
      <p>
        <a href="location.html"
           target="_top"><img src="images/location.gif"
             width="137"
             height="30"
             border="0"
             alt="Location"></a>
      </p>
      <p>
        <a href="schedule.html"
           target="_top"><img src="images/hours.gif"
             width="137"
             height="30"
             border="0"
             alt="Hours &amp; Events"></a>
      </p>
      <p>
        <a href="membership.html"
           target="_top"><img src="images/membership.gif"
             width="165"
             height="30"
             border="0"
             alt="Membership &amp; Fees"></a>
      </p>
      <p>
        <a href="swim_team.html"
           target="_top"><img src="images/swimteam.gif"
             width="137"
             height="30"
             border="0"
             alt="Swim Team"></a>
      </p>
      <p>
        <a href="board.html"
           target="_top"><img src="images/board.gif"
             width="137"
             height="30"
             border="0"
             alt="Board"></a>
      </p>
      <p>
        <a href="rentals.html"
           target="_top"><img src="images/rentals.gif"
             width="137"
             height="30"
             border="0"
             alt="Rentals &amp; Parties"></a>
      </p>
      <p>
        <a href="index.html"
           target="_top"><img src="images/home.gif"
             width="137"
             height="30"
             border="0"
             alt="Home"></a>
      </p>
</div>