<div class="rounded bubbles">
  <ul id="nav">
    <li><a href="index.php" class="current">Home</a></li>
    <li><a href="location.php">Location</a></li>
    <li><a href="schedule.php">Hours &amp; Events</a></li>
    <li><a href="membership.php">Membership &amp; Fees</a></li>
    <li><a href="swim_team.php">Swim Team</a></li>
    <li><a href="board.php">Board</a></li>
    <li><a href="rentals.php">Rentals &amp; Parties</a></li>
  </ul>
</div> 
